# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Work < Formula
  desc "Work - A CLI tool with git worktree management for parallel branch development"
  homepage "https://github.com/velvee-ai/ai-workflow"
  version "0.0.11"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/velvee-ai/ai-workflow/releases/download/v0.0.11/ai-workflow_0.0.11_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
    sha256 "78d1a80f689491da84d1129e05b4bce9b4106a4db138784247d81b3ba4132665"

    def install
      bin.install "work"

      # Generate and install shell completions
      bash_completion.install "completions/work.bash" => "work"
      zsh_completion.install "completions/_work"
      fish_completion.install "completions/work.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/velvee-ai/ai-workflow/releases/download/v0.0.11/ai-workflow_0.0.11_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
    sha256 "db3dcf768c4a1353893f73e4911d6568c6059e08458b6747822862ae9370c135"

    def install
      bin.install "work"

      # Generate and install shell completions
      bash_completion.install "completions/work.bash" => "work"
      zsh_completion.install "completions/_work"
      fish_completion.install "completions/work.fish"
    end
  end

  test do
    system "#{bin}/work", "--help"
  end
end
