# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Work < Formula
  desc "Work - A CLI tool with git worktree management for parallel branch development"
  homepage "https://github.com/velvee-ai/ai-workflow"
  version "0.0.17"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/velvee-ai/ai-workflow/releases/download/v0.0.17/ai-workflow_0.0.17_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
    sha256 "346ccd929f4de8fe9d46f14594dcd9f6b5228df073385b398cea26f153475644"

    def install
      bin.install "work"

      # Generate and install shell completions
      bash_completion.install "completions/work.bash" => "work"
      zsh_completion.install "completions/_work"
      fish_completion.install "completions/work.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/velvee-ai/ai-workflow/releases/download/v0.0.17/ai-workflow_0.0.17_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
    sha256 "d8e935fd283f38762877db02b133eb92743f39d9a49f44c3601cefa9f6bb313a"

    def install
      bin.install "work"

      # Generate and install shell completions
      bash_completion.install "completions/work.bash" => "work"
      zsh_completion.install "completions/_work"
      fish_completion.install "completions/work.fish"
    end
  end

  test do
    system "#{bin}/work", "--help"
  end
end
